const FETCHING = 'FETCHING'
const RESET_ERROR = 'RESET_ERROR'
const STORAGE_CLEANED = 'STORAGE_CLEANED'
const AUTH_EXPIRED = 'AUTH_EXPIRED'
const TIMEOUT_ERROR = 'TIMEOUT_ERROR'
const OFFLINE_ERROR = 'OFFLINE_ERROR'

export default {
  FETCHING,
  RESET_ERROR,
  STORAGE_CLEANED,
  AUTH_EXPIRED,
  TIMEOUT_ERROR,
  OFFLINE_ERROR
}
